name: Go Tests

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest

    container:
      image: node:20-bookworm

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.25'

      - name: Run Unit Test
        run: |
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Check Coverage Summary
        run: |
          go tool cover -func=coverage.out
