name: Go Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  run-unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest

    container:
      image: node:24-bookworm

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run Unit Test
        run: |
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Check Coverage Summary
        run: |
          go tool cover -func=coverage.out
